introduced breaking change Failure<T, E>
joanllenas/ngx-remotedata pull request #13
Opened 2020-01-28 01:34 UTC by elegon32

this is my proposal for the feature. #12 

I did not add unit tests yet...
But this seems to work in my project...

I changed some names which did not make sense to me anymore... 
What do you think?

2020-01-28 09:24 UTC, joanllenas commented on projects/lib/src/lib/remote-data.ts
> +  static of<T, E = DefaultError>(err: E, val?: T): RemoteData<T, E> {
I like the idea of `val` being optional, but we should change that also in the `InProgress` constructors

2020-01-28 09:25 UTC, joanllenas commented on projects/lib/src/lib/remote-data.ts
> +    if (val) {
This if/else statement is redundant, `new Failure(err, val);` does exactly the same

2020-01-28 09:26 UTC, joanllenas commented on projects/lib/src/lib/remote-data.ts
> +    if (this.val) {
This if/else statement is not necessary,  `return this.val;` does the same

2020-01-28 09:28 UTC, joanllenas requested changes
I added a couple of quick comments of things I noticed, tomorrow I'll actually download the PR and test it properly.
Thanks!

2020-01-29 18:47 UTC, joanllenas commented on projects/lib/src/lib/pipes.ts
> +export class GetRemoteDataPipe implements PipeTransform {
Let's rename this to `GetRemoteDataValuePipe` for consistency

2020-01-29 18:50 UTC, joanllenas requested changes
One last thing.
In the `app.module.ts` file, line 48, change:
```
            {
              matcher: (tag: string) => tag === RemoteDataTags.Failure,
              mapper: () => Failure.of(json.err)
            },
```
for
```
            {
              matcher: (tag: string) => tag === RemoteDataTags.Failure,
              mapper: () => Failure.of(json.err, json.val)
            },
```

2020-01-29 21:23 UTC, elegon32 commented
Done. I added some tests, too...
Do you change the version number accordingly to make it available via npm?
Thank you!

2020-01-30 07:25 UTC, joanllenas approved these changes
Looking good 👍

2020-01-30 07:26 UTC, merged